version: '3.6'
services:
  postgres:
    image: postgres
    container_name: pathmob-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pathmob
    ports:
      - "5432:5432"
    volumes:
      - "/var/lib/postgresql/data"