create table types (
id bigint generated by default as identity,
type varchar(255),
primary key (id)
);

create table pathologies (
id bigint generated by default as identity,
name varchar(255),
type_id bigint,
primary key (id)
);

create table subtypes (
id bigint generated by default as identity,
cut varchar(255),
hemodynamic varchar(255),
model varchar(255),
subtype varchar(255),
primary key (id)
);

create table pathologies_subtypes (
pathology_id bigint not null,
subtypes_id bigint not null
);

alter table pathologies_subtypes add constraint subtypes_id_uk unique (subtypes_id);
alter table pathologies add constraint type_id_fk foreign key (type_id) references types;
alter table pathologies_subtypes add constraint subtypes_id_fk foreign key (subtypes_id) references subtypes;
alter table pathologies_subtypes add constraint pathology_id_fk foreign key (pathology_id) references pathologies